language: objective-c  #1
osx_image: xcode7.3 #2
xcode_project: Contacts Picker.xcodeproj #3
xcode_scheme: Contacts Picker #4
xcode_sdk: iphonesimulator #5
script:
- xcodebuild -project "Contacts Picker.xcodeproj" -scheme "Contacts Picker" -sdk iphonesimulator build test
